version: '3'

services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
      - ./db/init:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always

  backend:
    build: ./backend/
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/kanjiCloud
    depends_on:
      - postgres
    volumes:
      - ./backend:/code:cached
    command: bash -c 'flask run --host=0.0.0.0 --port=5000 --debugger --reload'
  